### ISSUE TITLE
Сбор пожеланий

### ISSUE THREAD

**Issue by SonicGD** [SonicGD/bioengine#1]
@Dragnio и @Del-Vey давайте тут накидаем какой-то вменяем список того, что мы хотим получить от новой админки

**Comment by Dragnio** [comment]
1) Шапки новостей сделать сразу на странице игры. Чтобы сразу можно было залить набор и потом просто выбирать, а не как у нас сейчас. 
2) Стильно-модно-молодежно сделать "крутилку с играми в шапке" на БРК свободно редактируемой. Чтобы картинку там поменять или еще чего прям из админки. 
3) Новый стильный и клевый редактор автоматом ставящий один < p > в основе и в кате
4) На БРК убрать "Тэги" (все равно же не используем) и сделать необязательным "источник новости" аки на Нюке. 
5) Может автогенератор урлов новостей\статей\видео? 
6) Вернуть бэкапы и "редакции\diff'ы"
7) Вернуть просмотр голосовалок (архив). Сейчас нельзя ничего из старого посмотреть. 
8)

**Comment by Del-Vey** [comment]
1. Возможность добавлять второго разработчика игре (таких проектов на удивление дофига. Только за последний год четыре игры!).
2. Возможность загружать картинку для новости (шапку) прямо с раб. стола. Кнопка "Обзор", выбираем картинку, картинка автоматом загружается и в случае необходимости переименовывается.
3. На странице создания игры необходимо сделать возможность добавления тэгов, которые в последствие будут АВТОМАТИЧЕСКИ проставляться в каждой новости.
4. Вернуть взад бэкапы по версиям. Очень полезная была хуйня.
5. В каждой новости должна быть ссылка на игру формата "Игра: Dragon Age 2" (ссылка проставляется только на названии игры)
6. Архив голосований на сайте сделать было бы неплохо.
7. В админке и на странице игры сделать три ОТДЕЛЬНЫХ поля для даты выхода:
   - Дата выхода в США
   - Дата выхода в Европе
   - Дата выхода в России
8. "Режимы игры" нужно заменить на "Мультиплеер". В админке сделать кликер с двумя вариантами "Есть/Нет". И на этот раз не забудь про двоеточие!!!
9. На странице игры подвинуть инфу из правого столбца чуть влево, чтобы у "PlayStation 3" не переносилась на другую строку тройка. А то везде так.
10. На странице добавления разработчика заменить "Логотип для новостей" на "Логотип компании". Картинка должна отображаться на странице разработчика на сайте в описании, над текстом. Формат будет что-то в духе 668х300
11. На странице добавления разработчика убрать "Описание для новостей" вместе со всем полем и прочим. Лишнее явно.
12. Поиск по играм в админке! Я заебался среди трёх сотен игр постоянно вручную искать нужную!!!111oneone
13. Поиск по разработчикам тоже.
14. Half-Life 3 нам запилил быстро!

**Comment by SonicGD** [comment]
Ещё раз обращаю внимание, что вопрос по админке ;)

**Comment by Del-Vey** [comment]
Сделать так, чтобы во время создания страницы игры не было необходимости ПИСАТЬ ВРУЧНУЮ платформы, на которых выйдет игра. Реально заёбывает писать "PC, Xbox One, PlayStation 4, Xbox 360 и PlayStation 3".

Пусть будет список с чекерами и следующими платформами:
- PC
- Xbox One
- PlayStation 4
- Xbox 360
- PlayStation 3
- Xbox
- PlayStation 2
- PlayStation
- Wii U
